# Generated by Django 2.2.5 on 2020-08-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=500)),
                ('db', models.CharField(blank=True, max_length=100, null=True)),
                ('paginas', models.CharField(max_length=50)),
                ('fecha_publicado', models.DateField()),
                ('referencia_web', models.CharField(blank=True, max_length=100, null=True)),
                ('revista', models.CharField(max_length=200)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('impacto', models.FloatField()),
                ('indexado', models.BooleanField(default=False)),
                ('arbitrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=500)),
                ('base_datos', models.CharField(blank=True, max_length=100, null=True)),
                ('paginas', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_publicado', models.DateField()),
                ('referencia_web', models.URLField(blank=True, null=True)),
                ('editorial', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('capitulo', models.CharField(blank=True, max_length=50, null=True)),
                ('total_paginas', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiteraturaGris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=500)),
                ('fecha_publicado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=500)),
                ('aprobado_CC', models.BooleanField(default=False)),
                ('premios', models.CharField(blank=True, max_length=500, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('1', 'Primer Nivel'), ('2', 'Segundo Nivel'), ('3', 'Tercer Nivel')], max_length=40, null=True)),
                ('nivel_premio', models.CharField(blank=True, choices=[('CITMA', 'Ministerio de Ciencia, Tecnología y Medio Ambiente'), ('ACC', 'Academia de Ciencias'), ('MES', 'Ministerio de Educación Superior'), ('O', 'Otro')], max_length=40, null=True)),
            ],
            options={
                'ordering': ['titulo'],
                'db_table': 'resultados',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_costo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('jefe', models.CharField(blank=True, max_length=100, null=True)),
                ('dirigido_por_cfa', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=40)),
                ('nivel', models.CharField(blank=True, choices=[('PP', 'Programa Priorizado'), ('PE', 'Proyecto Empresarial'), ('Ift', 'Institucional ft'), ('I', 'Institucional')], max_length=40, null=True)),
                ('presupuesto_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('presupuesto_anno', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('entidad_ejecutora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajo_cientifico.Entidad')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajo_cientifico.Programa')),
                ('resultados', models.ManyToManyField(blank=True, to='trabajo_cientifico.Resultado')),
            ],
        ),
    ]
