# Generated by Django 2.2.5 on 2020-10-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_cientifico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, choices=[('CITMA', 'Ministerio de Ciencia, Tecnología y Medio Ambiente'), ('ACC', 'Academia de Ciencias'), ('MES', 'Ministerio de Educación Superior'), ('O', 'Otro')], max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='aprobado_CC',
            new_name='aprobado_cc',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='nivel_premio',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='doi',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='numero',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='volumen',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='capitulo',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='asdq', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='total_paginas',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='entidades',
            field=models.ManyToManyField(blank=True, null=True, related_name='entidades_participantes', to='trabajo_cientifico.Entidad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajo_cientifico.Programa'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resultados',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.Resultado'),
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='premios',
        ),
        migrations.AddField(
            model_name='resultado',
            name='premios',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.Premio'),
        ),
    ]
