# Generated by Django 2.2.16 on 2020-09-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_cientifico', '0002_auto_20200823_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resultado',
            options={},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='jefe',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='autores',
        ),
        migrations.AlterModelTable(
            name='resultado',
            table=None,
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Estatal', 'Estatal'), ('Comercial', 'Comercial')], max_length=20, null=True)),
                ('dim', models.CharField(blank=True, max_length=50, null=True)),
                ('centro_costo', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajo_cientifico.Entidad')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajo_cientifico.GrupoTrabajo')),
            ],
        ),
    ]
