# Generated by Django 2.2.16 on 2020-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_cientifico', '0003_auto_20200910_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='entidades',
            field=models.ManyToManyField(related_name='entidades_participantes', to='trabajo_cientifico.Entidad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='resultados',
            field=models.ManyToManyField(to='trabajo_cientifico.Resultado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='resultados',
            field=models.ManyToManyField(to='trabajo_cientifico.Resultado'),
        ),
    ]
