# Generated by Django 2.2.5 on 2020-08-23 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'Telefono'), ('M', 'Movil'), ('E', 'Correo'), ('F', 'Fax')], max_length=1)),
                ('descripcion', models.CharField(choices=[('P', 'Privado'), ('I', 'Institucional'), ('O', 'Otro')], max_length=20)),
                ('valor', models.CharField(choices=[('P', 'Privado'), ('I', 'Institucional'), ('O', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='human_resource.Persona')),
                ('foto', models.ImageField(null=True, upload_to='fotos_de_perfiles')),
                ('ci', models.CharField(blank=True, max_length=11, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True)),
                ('raza', models.CharField(blank=True, choices=[('B', 'Blanca'), ('M', 'Mestiza'), ('N', 'Negra')], max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('areas_interes', models.TextField(blank=True, max_length=500)),
                ('nivel_escolar', models.CharField(blank=True, choices=[('T/M', 'Técnico Medio'), ('S', 'Superior')], max_length=10, null=True)),
                ('especialidad', models.CharField(blank=True, choices=[('T', 'T'), ('E', 'E')], max_length=50, null=True)),
                ('grado_cientifico', models.CharField(blank=True, choices=[('MSc', 'Master en Ciencias'), ('Dr', 'Doctor en Ciencias')], max_length=3, null=True)),
                ('cateogoria_cientifica', models.CharField(blank=True, choices=[('AI', 'Aspirante a Investigador'), ('IA', 'Investigador Agregado'), ('IT', 'Investigador Titular')], max_length=25)),
                ('cateogoria_docente', models.CharField(blank=True, choices=[('Profesor Auxiliar', 'Auxiliar'), ('Profesor Agregado', 'Agregado'), ('Profesor Titular', 'Titular')], max_length=25, null=True)),
                ('tarjeta', models.IntegerField()),
                ('categoria_ocupacional', models.CharField(blank=True, choices=[('T', 'T'), ('E', 'E')], max_length=40, null=True)),
                ('fecha_entrada_insmet', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('motivos_salida', models.CharField(blank=True, max_length=500)),
                ('res_34_19', models.FloatField(blank=True, null=True)),
                ('msc_dr', models.FloatField(blank=True, null=True)),
                ('grupo_escala_antiguo', models.CharField(blank=True, choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI'), ('XVII', 'XVII'), ('XVIII', 'XVIII'), ('XIX', 'XIX'), ('XX', 'XX'), ('XXI', 'XXI'), ('XXII', 'XXII'), ('XXIII', 'XXIII'), ('XXIV', 'XXIV'), ('XXV', 'XXV')], max_length=5, null=True)),
                ('grupo_escala_actual', models.CharField(blank=True, choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI'), ('XVII', 'XVII'), ('XVIII', 'XVIII'), ('XIX', 'XIX'), ('XX', 'XX'), ('XXI', 'XXI'), ('XXII', 'XXII'), ('XXIII', 'XXIII'), ('XXIV', 'XXIV'), ('XXV', 'XXV')], max_length=5, null=True)),
                ('salario_escala_antiguo', models.FloatField(blank=True, null=True)),
                ('salario_escala_actual', models.FloatField(blank=True, default=0, null=True)),
                ('otros_pagos_antiguo', models.FloatField(blank=True, null=True)),
                ('otros_pagos_actual', models.FloatField(blank=True, null=True)),
                ('salario_total_antiguo', models.FloatField(blank=True, null=True)),
                ('salario_total_actual', models.FloatField(blank=True, default=0, null=True)),
                ('membresias', models.CharField(blank=True, max_length=200, null=True)),
                ('afiliaciones', models.ManyToManyField(blank=True, null=True, to='human_resource.Afiliacion')),
                ('contacto', models.ManyToManyField(to='human_resource.Contacto')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.Municipio')),
                ('plaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.Plaza')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('human_resource.persona',),
        ),
    ]
