# Generated by Django 2.2.16 on 2020-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='foto',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cateogoria_docente',
            field=models.CharField(blank=True, choices=[('PX', 'Profesor Auxiliar'), ('PA', 'Profesor Agregado'), ('PT', 'Profesor Titular')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nivel_escolar',
            field=models.CharField(blank=True, choices=[('TM', 'Técnico Medio'), ('S', 'Superior')], max_length=10, null=True),
        ),
    ]
