# Generated by Django 2.2.16 on 2020-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_auto_20200907_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_de_perfiles'),
        ),
    ]
