# Generated by Django 2.2.16 on 2020-09-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_trabajador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='afiliaciones',
        ),
    ]
