# Generated by Django 2.2.16 on 2020-09-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_cientifico', '0003_auto_20200910_1836'),
        ('human_resource', '0004_remove_trabajador_afiliaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='proyectos',
            field=models.ManyToManyField(to='trabajo_cientifico.Proyecto'),
        ),
    ]
