# Generated by Django 2.2.16 on 2020-09-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_cientifico', '0003_auto_20200910_1836'),
        ('human_resource', '0005_trabajador_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='afiliaciones',
            field=models.ManyToManyField(to='human_resource.Afiliacion'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='articulos',
            field=models.ManyToManyField(to='trabajo_cientifico.Articulo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='libros',
            field=models.ManyToManyField(to='trabajo_cientifico.Libro'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='servicios',
            field=models.ManyToManyField(to='trabajo_cientifico.Servicio'),
        ),
    ]
