# Generated by Django 2.2.16 on 2020-09-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0007_auto_20200910_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='afiliaciones',
            field=models.ManyToManyField(blank=True, null=True, to='human_resource.Afiliacion'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='articulos',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.Articulo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='certificaciones',
            field=models.ManyToManyField(blank=True, null=True, to='docencia.Certificacion'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='eventos',
            field=models.ManyToManyField(blank=True, null=True, to='docencia.Evento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='libros',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.Libro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='literatura_gris',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.LiteraturaGris'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='oponencias',
            field=models.ManyToManyField(blank=True, null=True, to='docencia.Oponencia'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='proyectos',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.Proyecto'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='resultados',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.Resultado'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='servicios',
            field=models.ManyToManyField(blank=True, null=True, to='trabajo_cientifico.Servicio'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tesis',
            field=models.ManyToManyField(blank=True, null=True, to='docencia.Tesis'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tribunales',
            field=models.ManyToManyField(blank=True, null=True, to='docencia.Tribunal'),
        ),
    ]
