# Generated by Django 2.2.5 on 2020-10-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0007_auto_20201008_1552'),
        ('human_resource', '0008_auto_20200927_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='ponencias',
            field=models.ManyToManyField(blank=True, null=True, to='docencia.Ponencia'),
        ),
    ]
