# Generated by Django 2.2.5 on 2020-10-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0009_trabajador_ponencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='areas_interes',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='membresias',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo',
            field=models.CharField(choices=[('T', 'Telefono'), ('M', 'Movil'), ('E', 'Correo'), ('F', 'Fax')], max_length=20),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cateogoria_cientifica',
            field=models.CharField(blank=True, choices=[('AI', 'Aspirante a Investigador'), ('IA', 'Investigador Agregado'), ('IT', 'Investigador Titular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cateogoria_docente',
            field=models.CharField(blank=True, choices=[('PX', 'Profesor Auxiliar'), ('PA', 'Profesor Agregado'), ('PT', 'Profesor Titular')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='grado_cientifico',
            field=models.CharField(blank=True, choices=[('MSc', 'Master en Ciencias'), ('Dr', 'Doctor en Ciencias')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='motivos_salida',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.Municipio'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nivel_escolar',
            field=models.CharField(blank=True, choices=[('TM', 'Técnico Medio'), ('S', 'Superior')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.Plaza'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='raza',
            field=models.CharField(blank=True, choices=[('B', 'Blanca'), ('M', 'Mestiza'), ('N', 'Negra')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='areas_de_interes',
            field=models.ManyToManyField(to='human_resource.AreasInteres'),
        ),
    ]
