# Generated by Django 2.2.5 on 2020-10-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0011_auto_20201014_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='contacto',
            field=models.ManyToManyField(blank=True, null=True, to='human_resource.Contacto'),
        ),
    ]
