# Generated by Django 2.2.5 on 2020-10-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_profesor', models.CharField(max_length=100)),
                ('cantidad_horas', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('centro_estudios', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('creditos', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=250)),
                ('nivel', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor_principal', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Articulo', 'Articulo'), ('Tesis', 'Tesis'), ('Proyecto', 'Proyecto'), ('Resultados', 'Resultados')], max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('S', 'Superior'), ('MSc', 'Master'), ('PhD', 'Doctorado')], max_length=3)),
                ('especialidad', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor_principal', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('participacion', models.CharField(choices=[('API_CO', 'Autor Principal Invitado por CO'), ('PAP', 'Ponente Autor Principal'), ('P', 'Ponente')], max_length=40)),
                ('autores', models.CharField(max_length=200)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docencia.Evento')),
            ],
        ),
    ]
