# Generated by Django 2.2.5 on 2020-10-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificacion',
            name='pais',
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='centro_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docencia.CentroEstudios'),
        ),
    ]
