# Generated by Django 2.2.16 on 2020-09-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificaciones',
            new_name='Certificacion',
        ),
    ]
