# Generated by Django 2.2.5 on 2020-10-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nivel',
            field=models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
