# Generated by Django 2.2.5 on 2020-10-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0004_auto_20201002_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
