# Generated by Django 2.2.5 on 2020-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0005_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='nivel',
            field=models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
