# Generated by Django 2.2.5 on 2020-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('B', 'Baja'), ('EU', 'En uso'), ('PB', 'Proceso de baja'), ('R', 'Roto')], max_length=20)),
                ('expediente_x', models.BooleanField(default=False)),
                ('inventario_contable', models.BooleanField(default=False)),
                ('medio_computacion', models.BooleanField(default=False)),
                ('carta_prestamo_in', models.FileField(blank=True, null=True, upload_to='')),
                ('carta_prestamo_out', models.FileField(blank=True, null=True, upload_to='')),
                ('prestado', models.BooleanField(default=False)),
                ('traslado', models.BooleanField(default=False)),
                ('carta_traslado_lugar', models.FileField(blank=True, null=True, upload_to='')),
                ('carta_traslado_economia', models.FileField(blank=True, null=True, upload_to='')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('identificador', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
