# Generated by Django 2.2.5 on 2020-11-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0001_initial'),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sindicato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.Trabajador'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centro.Local'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centro.Objeto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Proyecto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Trabajador'),
        ),
    ]
