# Generated by Django 2.2.5 on 2020-10-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0010_auto_20201013_2157'),
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='human_resource.Trabajador'),
        ),
    ]
