# Generated by Django 2.2.5 on 2020-11-19 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampoEspecialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CentroEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'Teléfono'), ('M', 'Móvil'), ('E', 'Correo'), ('F', 'Fax')], max_length=20)),
                ('descripcion', models.CharField(choices=[('P', 'Privado'), ('I', 'Institucional'), ('O', 'Otro')], max_length=20)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=500)),
                ('nivel', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centro.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('integrantes', gm2m.fields.GM2MField(related_name='grupos_trabajo', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoMasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoPolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('grupo_escala_antiguo', models.CharField(blank=True, choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI'), ('XVII', 'XVII'), ('XVIII', 'XVIII'), ('XIX', 'XIX'), ('XX', 'XX'), ('XXI', 'XXI'), ('XXII', 'XXII'), ('XXIII', 'XXIII'), ('XXIV', 'XXIV'), ('XXV', 'XXV')], max_length=10, null=True)),
                ('grupo_escala_actual', models.CharField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI'), ('XVII', 'XVII'), ('XVIII', 'XVIII'), ('XIX', 'XIX'), ('XX', 'XX'), ('XXI', 'XXI'), ('XXII', 'XXII'), ('XXIII', 'XXIII'), ('XXIV', 'XXIV'), ('XXV', 'XXV')], max_length=10)),
                ('salario_escala_antiguo', models.FloatField(blank=True, null=True)),
                ('salario_escala_actual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autores', gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='ponencias', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, choices=[('CITMA', 'Ministerio de Ciencia, Tecnología y Medio Ambiente'), ('ACC', 'Academia de Ciencias'), ('MES', 'Ministerio de Educación Superior'), ('O', 'Otro')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaExterna',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabajador.Persona')),
            ],
            bases=('trabajador.persona',),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('elementocientifico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabajador.ElementoCientifico')),
                ('aprobado_cc', models.BooleanField(default=False)),
                ('nivel', models.CharField(blank=True, choices=[('1', 'Primer Nivel'), ('2', 'Segundo Nivel'), ('3', 'Tercer Nivel')], max_length=40, null=True)),
                ('premios', models.ManyToManyField(blank=True, null=True, to='trabajador.Premio')),
            ],
            bases=('trabajador.elementocientifico',),
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('elementocientifico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabajador.ElementoCientifico')),
                ('grado', models.CharField(choices=[('S', 'Superior'), ('MSc', 'Master'), ('Dr', 'Doctorado')], max_length=3)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.CampoEspecialidad')),
            ],
            bases=('trabajador.elementocientifico',),
        ),
        migrations.CreateModel(
            name='Oponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('oponentes', gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='oponencias', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('base_datos', models.CharField(blank=True, max_length=100, null=True)),
                ('paginas', models.CharField(max_length=50)),
                ('fecha_publicado', models.DateField()),
                ('referencia_web', models.URLField(blank=True, null=True)),
                ('editorial', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('capitulo', models.CharField(max_length=50)),
                ('total_paginas', models.CharField(max_length=50)),
                ('autores', gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='libros', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Téc', 'Técnico'), ('Ing', 'Ingeniero'), ('Lic', 'Licenciado')], max_length=50)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.CampoEspecialidad')),
                ('centro_de_estudio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.CentroEstudios')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('cantidad_horas', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('creditos', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('centro_estudios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.CentroEstudios')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('miembros', gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='tribunales', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.Tesis')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabajador.Persona')),
                ('foto', models.ImageField(default='avatar_default.jpg', null=True, upload_to='fotos_de_perfiles/')),
                ('ci', models.CharField(max_length=11)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=20, null=True)),
                ('raza', models.CharField(blank=True, choices=[('B', 'Blanca'), ('M', 'Mestiza'), ('N', 'Negra')], max_length=20, null=True)),
                ('nivel_escolar', models.CharField(blank=True, choices=[('M', 'Medio'), ('S', 'Superior')], max_length=50, null=True)),
                ('grado_cientifico', models.CharField(blank=True, choices=[('MSc', 'Master en Ciencias'), ('Dr', 'Doctor en Ciencias')], max_length=50, null=True)),
                ('cateogoria_cientifica', models.CharField(blank=True, choices=[('AI', 'Aspirante a Investigador'), ('IA', 'Investigador Agregado'), ('IT', 'Investigador Titular')], max_length=50, null=True)),
                ('cateogoria_docente', models.CharField(blank=True, choices=[('PX', 'Profesor Auxiliar'), ('PA', 'Profesor Agregado'), ('PT', 'Profesor Titular')], max_length=50, null=True)),
                ('tarjeta', models.IntegerField(unique=True)),
                ('categoria_ocupacional', models.CharField(choices=[('T', 'Técnico'), ('E', 'Especialista')], max_length=20, null=True)),
                ('fecha_entrada_insmet', models.DateField(default=django.utils.timezone.now, null=True)),
                ('fecha_salida', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('motivos_salida', models.TextField(blank=True, max_length=1000, null=True)),
                ('res_34_19', models.FloatField(blank=True, null=True)),
                ('msc_dr', models.FloatField(blank=True, null=True)),
                ('otros_pagos_antiguo', models.FloatField(blank=True, null=True)),
                ('otros_pagos_actual', models.FloatField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('afiliaciones', models.ManyToManyField(blank=True, null=True, to='trabajador.OrganismoMasas')),
                ('areas_de_interes', models.ManyToManyField(blank=True, null=True, to='trabajador.AreaInteres')),
                ('certificaciones', models.ManyToManyField(blank=True, to='trabajador.Certificacion')),
                ('contacto', models.ManyToManyField(blank=True, null=True, to='trabajador.Contacto')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Especialidad')),
                ('membresias', models.ManyToManyField(blank=True, null=True, to='trabajador.OrganismoPolitico')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Municipio')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Oficina')),
                ('plaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Plaza')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('trabajador.persona',),
        ),
        migrations.AddField(
            model_name='tesis',
            name='graduado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Trabajador'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.CentroEstudios'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Estatal', 'Estatal'), ('Comercial', 'Comercial')], max_length=20, null=True)),
                ('dim', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.FloatField(default=0.0)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.CentroCosto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajador.Cliente')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajador.Entidad')),
                ('grupo_de_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajador.GrupoTrabajo')),
                ('resultados', models.ManyToManyField(blank=True, null=True, to='trabajador.Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('elementocientifico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabajador.ElementoCientifico')),
                ('object_id', models.PositiveIntegerField()),
                ('dirigido_por_cfa', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=40)),
                ('nivel', models.CharField(blank=True, choices=[('PP', 'Programa Priorizado'), ('PE', 'Proyecto Empresarial'), ('Ift', 'Institucional ft'), ('I', 'Institucional')], max_length=40, null=True)),
                ('presupuesto_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('presupuesto_anno', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2020, 11, 19, 9, 51, 31, 493292))),
                ('fecha_terminacion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.CentroCosto')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('entidad_ejecutora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Entidad')),
                ('entidades', models.ManyToManyField(blank=True, null=True, related_name='entidades_participantes', to='trabajador.Entidad')),
                ('grupo_de_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajador.GrupoTrabajo')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Programa')),
                ('resultados', models.ManyToManyField(blank=True, null=True, to='trabajador.Resultado')),
            ],
            bases=('trabajador.elementocientifico',),
        ),
        migrations.CreateModel(
            name='PonenciasRealizadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion', models.CharField(choices=[('API_CO', 'Autor Principal Invitado por CO'), ('PAP', 'Ponente Autor Principal'), ('P', 'Ponente')], max_length=40)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Evento')),
                ('ponencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Ponencia')),
                ('ponente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('integrantes', gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='comisiones', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('elementocientifico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabajador.ElementoCientifico')),
                ('doi', models.CharField(max_length=50)),
                ('db', models.CharField(blank=True, max_length=100, null=True)),
                ('paginas', models.CharField(max_length=50)),
                ('fecha_publicado', models.DateField()),
                ('referencia_web', models.URLField(blank=True, null=True)),
                ('revista', models.CharField(max_length=200)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('volumen', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('impacto', models.FloatField()),
                ('indexado', models.BooleanField(default=False)),
                ('arbitrado', models.BooleanField(default=False)),
                ('autores', gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='articulos', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
            ],
            bases=('trabajador.elementocientifico',),
        ),
    ]
