# Generated by Django 2.2.5 on 2020-10-20 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajo_cientifico', '0001_initial'),
        ('docencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'Teléfono'), ('M', 'Móvil'), ('E', 'Correo'), ('F', 'Fax')], max_length=20)),
                ('descripcion', models.CharField(choices=[('P', 'Privado'), ('I', 'Institucional'), ('O', 'Otro')], max_length=20)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoMasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoPolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_escala_antiguo', models.CharField(blank=True, choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI'), ('XVII', 'XVII'), ('XVIII', 'XVIII'), ('XIX', 'XIX'), ('XX', 'XX'), ('XXI', 'XXI'), ('XXII', 'XXII'), ('XXIII', 'XXIII'), ('XXIV', 'XXIV'), ('XXV', 'XXV')], max_length=10, null=True)),
                ('grupo_escala_actual', models.CharField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI'), ('XVII', 'XVII'), ('XVIII', 'XVIII'), ('XIX', 'XIX'), ('XX', 'XX'), ('XXI', 'XXI'), ('XXII', 'XXII'), ('XXIII', 'XXIII'), ('XXIV', 'XXIV'), ('XXV', 'XXV')], max_length=10)),
                ('salario_escala_antiguo', models.FloatField(blank=True, null=True)),
                ('salario_escala_actual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trabajador.Persona')),
                ('foto', models.ImageField(default='avatar_default.jpg', null=True, upload_to='fotos_de_perfiles')),
                ('ci', models.CharField(max_length=11)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=20)),
                ('raza', models.CharField(choices=[('B', 'Blanca'), ('M', 'Mestiza'), ('N', 'Negra')], max_length=20)),
                ('nivel_escolar', models.CharField(choices=[('TM', 'Técnico Medio'), ('S', 'Superior')], max_length=50)),
                ('especialidad', models.CharField(choices=[('T', 'Técnico'), ('E', 'Especialista')], max_length=50)),
                ('grado_cientifico', models.CharField(blank=True, choices=[('MSc', 'Master en Ciencias'), ('Dr', 'Doctor en Ciencias')], max_length=50, null=True)),
                ('cateogoria_cientifica', models.CharField(blank=True, choices=[('AI', 'Aspirante a Investigador'), ('IA', 'Investigador Agregado'), ('IT', 'Investigador Titular')], max_length=50, null=True)),
                ('cateogoria_docente', models.CharField(blank=True, choices=[('PX', 'Profesor Auxiliar'), ('PA', 'Profesor Agregado'), ('PT', 'Profesor Titular')], max_length=50, null=True)),
                ('tarjeta', models.IntegerField()),
                ('categoria_ocupacional', models.CharField(choices=[('T', 'Técnico'), ('E', 'Especialista')], max_length=20)),
                ('fecha_entrada_insmet', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('motivos_salida', models.TextField(blank=True, max_length=1000)),
                ('res_34_19', models.FloatField(blank=True, null=True)),
                ('msc_dr', models.FloatField(blank=True, null=True)),
                ('otros_pagos_antiguo', models.FloatField(blank=True, null=True)),
                ('otros_pagos_actual', models.FloatField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('afiliaciones', models.ManyToManyField(blank=True, to='trabajador.OrganismoMasas')),
                ('areas_de_interes', models.ManyToManyField(blank=True, to='trabajador.AreasInteres')),
                ('articulos', models.ManyToManyField(blank=True, to='trabajo_cientifico.Articulo')),
                ('certificaciones', models.ManyToManyField(blank=True, to='docencia.Certificacion')),
                ('contacto', models.ManyToManyField(blank=True, to='trabajador.Contacto')),
                ('eventos', models.ManyToManyField(blank=True, to='docencia.Evento')),
                ('libros', models.ManyToManyField(blank=True, to='trabajo_cientifico.Libro')),
                ('literatura_gris', models.ManyToManyField(blank=True, to='trabajo_cientifico.LiteraturaGris')),
                ('membresias', models.ManyToManyField(blank=True, to='trabajador.OrganismoPolitico')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Municipio')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Oficina')),
                ('oponencias', models.ManyToManyField(blank=True, to='docencia.Oponencia')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Plaza')),
                ('ponencias', models.ManyToManyField(blank=True, to='docencia.Ponencia')),
                ('proyectos', models.ManyToManyField(blank=True, to='trabajo_cientifico.Proyecto')),
                ('resultados', models.ManyToManyField(blank=True, to='trabajo_cientifico.Resultado')),
                ('servicios', models.ManyToManyField(blank=True, to='trabajo_cientifico.Servicio')),
                ('tesis', models.ManyToManyField(blank=True, to='docencia.Tesis')),
                ('tribunales', models.ManyToManyField(blank=True, to='docencia.Tribunal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('trabajador.persona',),
        ),
    ]
