# Generated by Django 2.2.5 on 2020-11-19 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='entidad_ejecutora',
            new_name='entidadejecutora',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='grupo_de_trabajo',
            new_name='grupo',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 14, 30, 23, 24170)),
        ),
    ]
