# Generated by Django 2.2.5 on 2020-11-19 20:34

import datetime
from django.db import migrations, models
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trabajador', '0002_auto_20201119_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='grupo_de_trabajo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='participantes',
            field=gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='proyectos', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
        migrations.AddField(
            model_name='servicio',
            name='participantes',
            field=gm2m.fields.GM2MField('trabajador.Trabajador', 'trabajador.PersonaExterna', related_name='servicios', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 15, 34, 11, 548625)),
        ),
        migrations.DeleteModel(
            name='GrupoTrabajo',
        ),
    ]
