# Generated by Django 2.2.5 on 2020-11-30 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0002_auto_20201130_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_aprobado',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 15, 52, 5, 392334)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 15, 52, 5, 392357)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 20, 52, 5, 397251, tzinfo=utc)),
        ),
    ]
