# Generated by Django 2.2.5 on 2020-11-20 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0003_auto_20201119_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='participacion',
            field=models.CharField(choices=[('AP', 'Autor Principal'), ('OA', 'Otro Autor'), ('C', 'Colaborador')], default='AP', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='doi',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='impacto',
            field=models.CharField(choices=[('I', 'Grupo I'), ('II', 'Grupo II'), ('III', 'Grupo III'), ('IV', 'Grupo IV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='issn',
            field=models.CharField(default=1234556, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='numero',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='volumen',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 20, 19, 33, 634886)),
        ),
    ]
