# Generated by Django 2.2.5 on 2020-11-30 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trabajador', '0003_auto_20201130_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_aprobado',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 16, 21, 9, 358502)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 16, 21, 9, 358523)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 21, 21, 9, 363391, tzinfo=utc)),
        ),
    ]
