# Generated by Django 2.2.5 on 2020-12-02 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0004_auto_20201130_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='edicion',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='estudiantes',
            field=models.ManyToManyField(related_name='cursos_recibidos', to='trabajador.Trabajador'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_aprobado',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 16, 19, 8, 421539)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 16, 19, 8, 421642)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 21, 19, 8, 439143, tzinfo=utc)),
        ),
    ]
