# Generated by Django 2.2.5 on 2020-11-20 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0004_auto_20201119_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 20, 20, 9, 46850)),
        ),
    ]
