# Generated by Django 2.2.5 on 2020-12-03 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0005_auto_20201202_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_aprobado',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 7, 6, 15, 849872)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 7, 6, 15, 849894)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 12, 6, 15, 854466, tzinfo=utc)),
        ),
    ]
