# Generated by Django 2.2.5 on 2020-11-20 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0005_auto_20201119_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='literatura_gris',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='literatura_gris',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 20, 23, 40, 894509)),
        ),
    ]
