# Generated by Django 2.2.5 on 2020-11-21 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0006_auto_20201119_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 12, 3, 30, 446115)),
        ),
    ]
