# Generated by Django 2.2.5 on 2020-12-03 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0006_auto_20201203_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_aprobado',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 14, 8, 54, 181553)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 14, 8, 54, 181572)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 19, 8, 54, 186176, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CertificarTrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Certificacion')),
                ('trabajador', models.ManyToManyField(related_name='certificaciones', to='trabajador.Trabajador')),
            ],
        ),
    ]
