# Generated by Django 2.2.5 on 2020-12-03 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0007_auto_20201203_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificartrabajador',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='certificartrabajador',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificaciones', to='trabajador.Trabajador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_aprobado',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 14, 24, 43, 408503)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 14, 24, 43, 408523)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 19, 24, 43, 413527, tzinfo=utc)),
        ),
    ]
