# Generated by Django 2.2.5 on 2020-11-25 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0007_auto_20201121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 9, 47, 57, 115153)),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nivel',
            field=models.CharField(choices=[('1', 'Primer Nivel'), ('2', 'Segundo Nivel'), ('3', 'Tercer Nivel')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tesis',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='categoria_ocupacional',
            field=models.CharField(choices=[('T', 'Técnico'), ('E', 'Especialista')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Especialidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_entrada_insmet',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nivel_escolar',
            field=models.CharField(choices=[('M', 'Medio'), ('S', 'Superior')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='oficina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Oficina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='plaza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='trabajador.Plaza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='raza',
            field=models.CharField(choices=[('B', 'Blanca'), ('M', 'Mestiza'), ('N', 'Negra')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.Tesis')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.Trabajador')),
            ],
        ),
    ]
