# Generated by Django 2.2.5 on 2020-11-25 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0008_auto_20201125_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 10, 0, 20, 443709)),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='trabajador.Trabajador'),
        ),
    ]
