# Generated by Django 2.2.5 on 2020-12-03 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0008_auto_20201203_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_aprobado',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 16, 30, 14, 24888)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 16, 30, 14, 24907)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 21, 30, 14, 29555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_de_perfiles'),
        ),
    ]
