# Generated by Django 2.2.5 on 2020-11-25 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trabajador', '0009_auto_20201125_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesis',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='graduado',
        ),
        migrations.AddField(
            model_name='tesis',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tesis',
            name='fecha_culminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesis',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 11, 31, 36, 649664)),
        ),
    ]
