# Generated by Django 2.2.5 on 2020-11-25 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0010_auto_20201125_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 12, 29, 20, 237552)),
        ),
    ]
